//
//  defines.h
//  SensorFuse
//
//  Created by Jonas Fehr on 21/02/2018.
//

#pragma once

#define PORT 49161
#define NUM_MSG_STRINGS 30
#define NUM_GATE_DISPLAY 100
#define DEBUG 0
#define NUMBER_OF_SOUNDOBJECTS 6

#define SENDHOST "localhost"
#define SENDPORT_VISUAL 49162
#define SENDPORT_AUDIO 49163
#define RECEIVEPORT_FLOCKING 49170
#define SENDPORT_FLOCKING 49171
#define LASTARTNETADDR 32

#define NUM_GATES 40
#define SPACING_ENDS 4
#define SPACING_SIDE 5
#define INSTALLATION_LENGTH (NUM_GATES-1)*2
#define INSTALLATION_WIDTH 4

#define TOTAL_LENGTH (INSTALLATION_LENGTH+2*SPACING_ENDS)
#define TOTAL_WIDTH (INSTALLATION_WIDTH+2*SPACING_SIDE)
#define HALF_TOTAL_LENGTH (TOTAL_LENGTH/2)
#define HALF_TOTAL_WIDTH (TOTAL_WIDTH/2)

#define RATIO_START  (SPACING_ENDS/TOTAL_WIDTH)
